[package]

name = "lever"
version = "0.0.1"
authors = [ "errordeveloper@gmail.com" ]

[[bin]]

name = "lever"
path = "src/lever.rs"

[[bin]]

name = "handle"
path = "src/handle.rs"

[dependencies.hammer]

version = "0.1.0"
git = "https://github.com/wycats/hammer.rs"
